### ISSUE TITLE
Training part "IndexError: too many indices for array"

### ISSUE THREAD

**Issue by Licko0909** [acburigo/CapsNet#1]
There has been no error in the front. Until the training phase, the following error occurred. Can you give me some help?
![image](https://user-images.githubusercontent.com/27897166/50571163-09cf6b80-0dde-11e9-8e9b-f24a79331bb6.png)

**Comment by PrzemekCichy** [comment]
I have the same issue.

**Comment by acburigo** [comment]
Hey. It's been a long time I don't touch this. It is probably a PyTorch issue. I think, at the time, we were on PyTorch 0.4 or something. Have you tried removing the `[0]`?

**Comment by PrzemekCichy** [comment]
Hi, yes I've done that in this and few other lines and it fixed the issues.

**Comment by Harsh9524** [comment]
> Hey. It's been a long time I don't touch this. It is probably a PyTorch issue. I think, at the time, we were on PyTorch 0.4 or something. Have you tried removing the `[0]`?

Thank you! I had the same issue and removing [0] from line 14,15 and 16 fixed it.

**Comment by acburigo** [comment]
I have just committed the fix suggestions. Thanks, everyone!
